export const ACTION_WITHDRAW_MONEY="ACTION_WITHDRAW_MONEY";
export const ACTION_DEPOSIT_MONEY="ACTION_DEPOSIT_MONEY";
export const ACTION_CHANGE_PIN="ACTION_CHANGE_PIN";
export const ACTION_GET_CURRENT_BALANCE="ACTION_GET_CURRENT_BALANCE"